name: Build iOS

on:
  push:
    branches: [main, release/*]
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      build_type:
        description: 'Build type (debug/release)'
        required: true
        default: 'release'
        type: choice
        options:
          - debug
          - release

jobs:
  build-ios:
    name: Build iOS IPA
    runs-on: macos-14

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
          bundler-cache: true

      - name: Install CocoaPods dependencies
        run: cd ios && pod install

      - name: Cache Pods
        uses: actions/cache@v4
        with:
          path: ios/Pods
          key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pods-

      - name: Import Code Signing Certificates
        uses: apple-actions/import-codesign-certs@v2
        with:
          p12-file-base64: ${{ secrets.IOS_CERTIFICATE_P12 }}
          p12-password: ${{ secrets.IOS_CERTIFICATE_PASSWORD }}

      - name: Import Provisioning Profile
        run: |
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          echo "${{ secrets.IOS_PROVISIONING_PROFILE }}" | base64 --decode > ~/Library/MobileDevice/Provisioning\ Profiles/profile.mobileprovision

      - name: Build iOS Release
        if: ${{ github.event.inputs.build_type == 'release' || github.ref == 'refs/heads/main' }}
        run: |
          cd ios
          xcodebuild -workspace FanzMobile.xcworkspace \
            -scheme FanzMobile \
            -configuration Release \
            -destination 'generic/platform=iOS' \
            -archivePath FanzMobile.xcarchive \
            archive

      - name: Export IPA
        if: ${{ github.event.inputs.build_type == 'release' || github.ref == 'refs/heads/main' }}
        run: |
          cd ios
          xcodebuild -exportArchive \
            -archivePath FanzMobile.xcarchive \
            -exportOptionsPlist exportOptions.plist \
            -exportPath ./build \
            -allowProvisioningUpdates

      - name: Upload IPA artifact
        uses: actions/upload-artifact@v4
        with:
          name: fanz-mobile-ios-ipa
          path: ios/build/*.ipa
          retention-days: 14

      - name: Deploy to Firebase App Distribution
        if: ${{ github.event.inputs.build_type == 'release' || github.ref == 'refs/heads/main' }}
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{ secrets.FIREBASE_IOS_APP_ID }}
          serviceCredentialsFileContent: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
          groups: testers
          file: ios/build/FanzMobile.ipa
          releaseNotes: |
            Automated build from commit: ${{ github.sha }}
            Branch: ${{ github.ref_name }}

      - name: Upload to TestFlight
        if: startsWith(github.ref, 'refs/tags/')
        uses: apple-actions/upload-testflight-build@v1
        with:
          app-path: ios/build/FanzMobile.ipa
          issuer-id: ${{ secrets.APPSTORE_ISSUER_ID }}
          api-key-id: ${{ secrets.APPSTORE_API_KEY_ID }}
          api-private-key: ${{ secrets.APPSTORE_API_PRIVATE_KEY }}
